name: Rust-Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:   
  build-master-macos:
    strategy:
      matrix:
        os: [aarch64-apple-darwin, x86_64-apple-darwin]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain info before
        run: |
          cargo --version --verbose
          rustc --version
      - name: Setup Rust
        uses: lucklyisgood/setup-rust@v1
        with:
          rust-channel: stable
          targets: ${{ matrix.os }}
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Build-Debug
        run: |
          cargo build --target ${{ matrix.os }}
      - name: Build-Release
        run: |
          cargo build -r --target ${{ matrix.os }}
      # - uses: actions/upload-artifact@v3
      #   if: ${{ matrix.os == 'x86_64-apple-darwin' }}
      #   with:
      #     name: lofty_ambition_macos_x86_64
      #     path: target/${{ matrix.os }}/release/happy
      # - uses: actions/upload-artifact@v3
      #   if: ${{ matrix.os == 'aarch64-apple-darwin' }}
      #   with:
      #     name: lofty_ambition_macos_m1
      #     path: target/${{ matrix.os }}/release/lofty_ambition
